### ISSUE TITLE
Auto routes help

### ISSUE THREAD

**Issue by theRemix** [fponticelli/restx#15]
i set up a repo to test out restx and ran into an error

```
@:path("/blog/:id")
  function show( id:Int ) {
    response.send( { id : id } );
  }
```

errors with

```
Error: Parameter "id" is required
   at Array.<anonymous> (/app/bin/app.js:324:10)
   at Object.thx.promise.Future.update (/app/bin/app.js:685:63)
   at Object.thx.promise.Future.then (/app/bin/app.js:657:8)
   at Object.restx.RouteProcess.run (/app/bin/app.js:314:66)
   at f (/app/bin/app.js:766:242)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)
   at next (/app/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/app/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)
   at /app/node_modules/express/lib/router/index.js:267:22
```

here is the full source for how i set it up and compiled  
https://github.com/theRemix/restx_jade

here is the app deployed so you can see the results  
http://restx-jade.herokuapp.com/  
http://restx-jade.herokuapp.com/blog  
_then this breaks_  
http://restx-jade.herokuapp.com/blog/123

how can i fix this?

**Comment by fponticelli** [comment]
Can you test again? Note that `@:path()` is now `@:get()`.

**Comment by theRemix** [comment]
ah i see, accepted PR  
thanks! it works great  

http://restx-jade.herokuapp.com/blog/123
